export enum ValidateForm {
    SHOULD_NOT_EMPTY = "Should not be empty",
    SHOULD_BE_STRING = "Should be a string",
    INVALID_EMAIL_FORMAT = "รูปแบบอีเมลไม่ถูกต้อง",
    MISMATCH = "รูปแบบข้อมูลไม่ถูกต้อง",
    MUST_BE_UUID = "Must be uuid",
    MUST_BE_CHARACTERS = "ต้องเป็นตัวอักษรเท่านั้น",
    MUST_BE_NUMBERS = "ต้องเป็นตัวเลขเท่านั้น",
    MUST_BE_BOOLEAN = "Must be boolean",
    MUST_BE_PHONE_NUMBER = "Must be a phone number",
    NAME_MUST_NOT_EXCEED_THAN_50_CHAR = "Must not exceed more than 50 characters",
    NAME_MUST_HAVE_AT_LEAST_1_CHAR = "Must have at least 1 character",
    PASSWORD_NOT_EXCEED_MORE_THAN_60_CHAR = "Must not exceed more than 60 characters",
    PASSWORD_MUST_HAVE_AT_LEAST_8_CHAR = "Must have at least 8 characters",
    PASSWORD_MUST_HAVE_AT_LEAST_1_LOWER_CASE = "Must have at least 1 lower case letter",
    PASSWORD_MUST_HAVE_AT_LEAST_1_UPPER_CASE = "Must have at least 1 upper case letter",
    PASSWORD_MUST_HAVE_AT_LEAST_1_NUMBER = "Must have at least 1 number",
    PASSWORD_MUST_HAVE_AT_LEAST_1_SPECIAL_CHAR = "Must have at least 1 special character",
    ORDER_MUST_BE_ASC_OR_DESC = "Must be ASC or DESC",
}
